# Databricks notebook source
config = [
{
	'PartitionKey': '1',
	'RowKey': '1',
	'ACTIVE': True,
	'FILE_NAME': 'Fx Rates.CSV',
	'FOLDER_NAME': 'GSC_Extracts/QV/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'RateCode,RateMonth',
	'PUBLISH': True,
	'TABLE_NAME': 'FX_RATES'
}, 
{
	'PartitionKey': '1',
	'RowKey': '2',
	'ACTIVE': False,
	'FILE_NAME': 'Fx Rates Hist.CSV',
	'FOLDER_NAME': 'Data_Lake/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'RateCode,RateMonth',
	'PUBLISH': True,
	'TABLE_NAME': 'FX_RATES_HIST'
}, 
{
	'PartitionKey': '1',
	'RowKey': '3',
	'ACTIVE': False,
	'FILE_NAME': 'budget exchange rates.csv',
	'FOLDER_NAME': 'Budget/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'Currency,FiscalYear',
	'PUBLISH': True,
	'TABLE_NAME': 'FX_BUDGET_RATES'
}, 
{
	'PartitionKey': '1',
	'RowKey': '4',
	'ACTIVE': False,
	'FILE_NAME': 'Budget FY21 ABL QV.csv',
	'FOLDER_NAME': 'Budget/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'CustomerCode, ShipToDeliveryLocationID, ProductNumber, Month',
	'PUBLISH': True,
	'TABLE_NAME': 'Budget_ABL'
}, 
{
	'PartitionKey': '1',
	'RowKey': '5',
	'ACTIVE': False,
	'FILE_NAME': 'Budget FY21 Hercules QV.csv',
	'FOLDER_NAME': 'Budget/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'CustomerCode, ShipToDeliveryLocationID, ProductNumber, Month',
	'PUBLISH': True,
	'TABLE_NAME': 'Budget_HERCULES'
}, 
{
	'PartitionKey': '1',
	'RowKey': '6',
	'ACTIVE': False,
	'FILE_NAME': 'Budget Mexico FY20.csv',
	'FOLDER_NAME': 'Budget/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'CustomerCode, ShipToDeliveryLocationID, ProductNumber, Month',
	'PUBLISH': True,
	'TABLE_NAME': 'Budget_Mexico'
}, 
{
	'PartitionKey': '1',
	'RowKey': '7',
	'ACTIVE': False,
	'FILE_NAME': 'Budget OLAC FY20.csv',
	'FOLDER_NAME': 'Budget/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'CustomerCode, ShipToDeliveryLocationID, ProductNumber, Month',
	'PUBLISH': True,
	'TABLE_NAME': 'Budget_OLAC'
}, 
{
	'PartitionKey': '1',
	'RowKey': '8',
	'ACTIVE': False,
	'FILE_NAME': 'SAPOpenSalesOrders.csv',
	'FOLDER_NAME': 'GSC_Extracts/QV/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'SONumber, SOLine',
	'PUBLISH': True,
	'TABLE_NAME': 'SAPOpenSalesOrders'
}, 
{
	'PartitionKey': '1',
	'RowKey': '9',
	'ACTIVE': False,
	'FILE_NAME': 'grainger_conversion_table.csv',
	'FOLDER_NAME': 'GSC_Extracts/QV/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'GraingerSKU',
	'PUBLISH': True,
	'TABLE_NAME': 'grainger_conversion_table'
}, 
{
	'PartitionKey': '1',
	'RowKey': '10',
	'ACTIVE': False,
	'FILE_NAME': 'time_dimension.csv',
	'FOLDER_NAME': 'GSC_Extracts/QV/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'KEY_COLUMNS': 'dayID',
	'PUBLISH': True,
	'TABLE_NAME': 'time_dimension'
}, 
{
	'PartitionKey': '1',
	'RowKey': '11',
	'ACTIVE': True,
	'FILE_NAME': 'SAP_Inventory_Valuation_Extract.CSV',
	'FOLDER_NAME': 'GSC_Extracts/QV/',
	'HANDLE_DELETE': False,
	'HEADER': True,
	'PUBLISH': True,
	'TABLE_NAME': 'sap_inventory_valuation_extract'
}, 
{
	'PartitionKey': '1',
	'RowKey': '12',
	'ACTIVE': False,
    'FILE_NAME': 'Grainger_Data_Export_2019.csv',
    'FOLDER_NAME': 'Data_Lake/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'Grainger_2019'
}, 
{
	'PartitionKey': '1',
	'RowKey': '13',
	'ACTIVE': False,
    'FILE_NAME': 'Grainger_Data_Export_2020.csv',
    'FOLDER_NAME': 'Data_Lake/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'Grainger_2020'
}, 
{
	'PartitionKey': '1',
	'RowKey': '14',
	'ACTIVE': True,
    'FILE_NAME': 'Exclusion_List.csv',
    'FOLDER_NAME': 'skybot/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': 'EBSOperatingUnit,  AccountNumber, PartyId, RegistrationID, BillToCountryRegion',
    'PUBLISH': True,
    'TABLE_NAME': 'Exclusion_List'
}, 
{
	'PartitionKey': '1',
	'RowKey': '15',
	'ACTIVE': True,
    'FILE_NAME': 'Grainger_POS.csv',
    'FOLDER_NAME': 'skybot/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'Grainger_POS'
}, 
{
	'PartitionKey': '1',
	'RowKey': '16',
	'ACTIVE': True,
    'FILE_NAME': 'Henri_Schein.csv',
    'FOLDER_NAME': 'skybot/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'Henri_Schein_POS'
}, 
{
	'PartitionKey': '1',
	'RowKey': '17',
	'ACTIVE': True,
    'FILE_NAME': 'NDC.csv',
    'FOLDER_NAME': 'skybot/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'NDC_POS'
}, 
{
	'PartitionKey': '1',
	'RowKey': '18',
	'ACTIVE': False,
    'FILE_NAME': 'WC_PROCON_ALL_CONTRACTS_A.csv',
    'FOLDER_NAME': 'Data_Lake/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'WC_PROCON_ALL_CONTRACTS_A'
}, 
{
	'PartitionKey': '1',
	'RowKey': '19',
    'ACTIVE': False,
    'FILE_NAME': 'WC_TM_US_ZIP_CODES_H.csv',
    'FOLDER_NAME': 'Data_Lake/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'WC_TM_US_ZIP_CODES_H'
},
{
    'PartitionKey': '1',
    'RowKey': '20',
    'ACTIVE': False,
    'FILE_NAME': 'WC_QV_POS_EXCLUDED_CUSTOMER_H.CSV',
    'FOLDER_NAME': 'Data_Lake/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'WC_QV_POS_EXCLUDED_CUSTOMER_H'
},
{
    'PartitionKey': '1',
    'RowKey': '21',
    'ACTIVE': True,
    'FILE_NAME': 'ScheinCAD.csv',
    'FOLDER_NAME': 'skybot/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'Henri_Schein_CAD_POS'
},
{
    'PartitionKey': '1',
    'RowKey': '22',
    'ACTIVE': True,
    'FILE_NAME': 'MAN_ADJ.csv',
    'FOLDER_NAME': 'skybot/',
    'HANDLE_DELETE': False,
    'HEADER': True,
    'KEY_COLUMNS': '',
    'PUBLISH': True,
    'TABLE_NAME': 'Man_Adj_POS'
}]

# COMMAND ----------


