# Databricks notebook source
config = [
{
	'PartitionKey': '1',
	'RowKey': '1',
	'ACTIVE': False,
    'HANDLE_DELETE': False,
    'HARD_DELETE': False,
	'APPLICATION': 'TICKET',
	'FILE_NAME': 'MD.TICKET.WORKLOADMDM2.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'WORKLOADMDM2',
	'PUBLISH': True,
	'TABLE_NAME': 'MD_TICKET_WORKLOADMDM2',
	'WORKSPACE': 'MD',
    'ESCAPE_CHAR': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '2',
	'ACTIVE': False,
    'HANDLE_DELETE': False,
    'HARD_DELETE': False,
	'APPLICATION': 'TICKET',
	'FILE_NAME': 'GUAF.TICKET.ITINFRAGUAF.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'ITINFRAGUAF',
	'PUBLISH': True,
	'TABLE_NAME': 'GUAF_TICKET_ITINFRAGUAF',
	'WORKSPACE': 'GUAF',
    'ESCAPE_CHAR': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '3',
	'ACTIVE': True,
    'HANDLE_DELETE': True,
    'HARD_DELETE': True,
	'APPLICATION': 'CR',
	'FILE_NAME': 'EV.CR.CSEXPORT2DL.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'CSEXPORT2DL',
	'PUBLISH': True,
	'TABLE_NAME': 'EV_CR_CSEXPORT2DL',
	'WORKSPACE': 'EV',
    'ESCAPE_CHAR': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '4',
	'ACTIVE': False,
    'HANDLE_DELETE': False,
    'HARD_DELETE': False,
	'APPLICATION': 'CR',
	'FILE_NAME': 'EV.CR.TRASH.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'TRASH',
	'PUBLISH': True,
	'TABLE_NAME': 'EV_CR_TRASH',
	'WORKSPACE': 'EV',
    'ESCAPE_CHAR': ''
},
{
	'PartitionKey': '1',
	'RowKey': '5',
	'ACTIVE': True,
    'HANDLE_DELETE': False,
    'HARD_DELETE': False,
	'APPLICATION': 'CR',
	'FILE_NAME': 'CNAFQA.CR.QARA Dashboard.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'QARADASHBOARD1',
	'PUBLISH': True,
	'TABLE_NAME': 'QARA_DASHBOARD',
	'WORKSPACE': 'CNAFQA',
    'ESCAPE_CHAR': '"'
},
{
	'PartitionKey': '1',
	'RowKey': '6',
	'ACTIVE': True,
    'HANDLE_DELETE': True,
    'HARD_DELETE': True,
	'APPLICATION': 'REQ',
	'FILE_NAME': 'COE.REQ.DATALAKE.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'DATALAKE',
	'PUBLISH': True,
	'TABLE_NAME': 'COE_PLAN_DATA',
	'WORKSPACE': 'COE',
    'ESCAPE_CHAR': '"'
},
{
	'PartitionKey': '1',
	'RowKey': '7',
	'ACTIVE': True,
    'HANDLE_DELETE': True,
    'HARD_DELETE': True,
	'APPLICATION': 'TRAINING',
	'FILE_NAME': 'COE.TRAINING.DATALAKE.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'DATALAKE',
	'PUBLISH': True,
	'TABLE_NAME': 'COE_TRAINING',
	'WORKSPACE': 'COE',
    'ESCAPE_CHAR': '"'
},
{
	'PartitionKey': '1',
	'RowKey': '8',
	'ACTIVE': True,
    'HANDLE_DELETE': True,
    'HARD_DELETE': True,
	'APPLICATION': 'TRSTEP',
	'FILE_NAME': 'COE.TRSTEP.DATALAKE.csv',
	'KEY_COLUMNS': 'Id',
	'LIST_NAME': 'DATALAKE',
	'PUBLISH': True,
	'TABLE_NAME': 'COE_TRSTEP',
	'WORKSPACE': 'COE',
    'ESCAPE_CHAR': '"'
}]
