# Databricks notebook source
config = [
# {
# 	'PartitionKey': '1',
# 	'RowKey': '1',
# 	'ACTIVE': True,
# 	'INCREMENTAL': False,
# 	'NOTEBOOK_LEVEL': 1,
# 	'NOTEBOOK_NAME': 'ACCOUNT_COL',
# 	'PRUNE_DAYS': 10,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_COL',
# 	'UC': True
# }, 
# {
# 	'PartitionKey': '1',
# 	'RowKey': '2',
# 	'ACTIVE': True,
# 	'INCREMENTAL': True,
# 	'NOTEBOOK_LEVEL': 1,
# 	'NOTEBOOK_NAME': 'ACCOUNT_EBS',
# 	'PRUNE_DAYS': 10,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_EBS',
# 	'UC': True
# }, 
# {
# 	'PartitionKey': '1',
# 	'RowKey': '3',
# 	'ACTIVE': False,
# 	'INCREMENTAL': False,
# 	'NOTEBOOK_LEVEL': 2,
# 	'NOTEBOOK_NAME': 'ACCOUNT_PRMS',
# 	'PRUNE_DAYS': 10,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_PRMS',
# 	'UC': True
# }, 
# {
# 	'PartitionKey': '1',
# 	'RowKey': '4',
# 	'ACTIVE': True,
# 	'INCREMENTAL': True,
# 	'NOTEBOOK_LEVEL': 2,
# 	'NOTEBOOK_NAME': 'ACCOUNT_SAP',
# 	'PRUNE_DAYS': 1,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_SAP',
# 	'UC': True
# }, 
# {
# 	'PartitionKey': '1',
# 	'RowKey': '5',
# 	'ACTIVE': True,
# 	'INCREMENTAL': False,
# 	'NOTEBOOK_LEVEL': 2,
# 	'NOTEBOOK_NAME': 'ACCOUNT_TOT',
# 	'PRUNE_DAYS': 10,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_TOT',
# 	'UC': True
# }, 
{
	'PartitionKey': '1',
	'RowKey': '6',
	'ACTIVE': False,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'BILL_TO_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'BILL_TO_SAP',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '7',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'CUSTOMER_ITEMS_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_ITEMS_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '8',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'DATE',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'DATE',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '9',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'EXCHANGE_RATE_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'EXCHANGE_RATE_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '10',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'EXCHANGE_RATE_QV',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'EXCHANGE_RATE_QV',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '11',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'GROUPINGS_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'GROUPINGS_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '12',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'ORGANIZATION_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_COL',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '13',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'ORGANIZATION_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '14',
	'ACTIVE': False,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'ORGANIZATION_PRMS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_PRMS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '15',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'ORGANIZATION_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_SAP',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '16',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'ORGANIZATION_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '17',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_COL',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '18',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '19',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_MDM',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_MDM',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '20',
	'ACTIVE': False,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_PRMS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_PRMS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '21',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_QV',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_QV',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '22',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_SAP',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '23',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '24',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_TWD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_TWD',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '25',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PUBLIC_HOLIDAYS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PUBLIC_HOLIDAYS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '26',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_BUDGET_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_BUDGET_COL',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '27',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_BUDGET_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_BUDGET_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '28',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_BUDGET_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_BUDGET_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '29',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_ORGANIZATION_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_ORGANIZATION_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '30',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'CUSTOMER_LOCATION_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_LOCATION_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '31',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'CUSTOMER_LOCATION_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_LOCATION_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '32',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_COL',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '33',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '34',
	'ACTIVE': False,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_PRMS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_PRMS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '35',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_SAP',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '36',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_TOT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '37',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SUPPLIER_ACCOUNT_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SUPPLIER_ACCOUNT_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '38',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'USER_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'USER_EBS',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '39',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SUPPLIER_ACCOUNT_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'SUPPLIER_ACCOUNT_SAP',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '40',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PARTY_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PARTY_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '41',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TERRITORY_ASSIGNMENTS_SS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_ASSIGNMENTS_SS',
	'UC': False
},
{
    'PartitionKey': '1',
    'RowKey': '42',
    'ACTIVE': True,
    'INCREMENTAL': False,
    'NOTEBOOK_LEVEL': 1,
    'NOTEBOOK_NAME': 'PRODUCT_REGION_MDM',
    'PRUNE_DAYS': 10,
    'PUBLISH': True,
    'TABLE_NAME': 'PRODUCT_REGION_MDM',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '43',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'CUSTOMER_LOCATION_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_LOCATION_COL',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '44',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'PRODUCT_SF',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_SF',
	'UC': False
}, 
# {
# 	'PartitionKey': '1',
# 	'RowKey': '45',
# 	'ACTIVE': True,
# 	'INCREMENTAL': True,
# 	'NOTEBOOK_LEVEL': 1,
# 	'NOTEBOOK_NAME': 'ACCOUNT_SF',
# 	'PRUNE_DAYS': 10,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_SF',
# 	'UC': True
# },
{
	'PartitionKey': '1',
	'RowKey': '46',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'USER_SF',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'USER_SF',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '47',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'ORIGIN_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORIGIN_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '48',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'ORGANIZATION_PDH',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '49',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'ORIGIN_PDH',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORIGIN_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '50',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'USER_PDH',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'USER_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '51',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_PDH',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '52',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_PDH',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '53',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORIGIN_PDH',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORIGIN_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '54',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '55',
	'ACTIVE': False,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_SAPQV',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_SAPQV',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '56',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'EXCHANGE_RATE_BUD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'EXCHANGE_RATE_BUD',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '57',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'LEDGER_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'LEDGER_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '58',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORIGIN_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORIGIN_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '59',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SUPPLIER_LOCATION_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SUPPLIER_LOCATION_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '60',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PAYMENT_TERMS_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PAYMENT_TERMS_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '61',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PAYMENT_METHODS_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PAYMENT_METHODS_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '62',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TERRITORY_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '63',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'AVERAGE_UNIT_PRICE_SAPQV',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'AVERAGE_UNIT_PRICE_SAPQV',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '64',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_FORECAST_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_FORECAST_COL',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '65',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_FORECAST_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_FORECAST_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '66',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SALES_FORECAST_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_FORECAST_TOT',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '67',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'CUSTOMER_SALES_ORGANIZATION_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_SALES_ORGANIZATION_COL',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '68',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'CUSTOMER_SALES_ORGANIZATION_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_SALES_ORGANIZATION_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '69',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'CUSTOMER_SALES_ORGANIZATION_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_SALES_ORGANIZATION_TOT',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '70',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'ACCOUNT_ORGANIZATION_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'ACCOUNT_ORGANIZATION_SAP',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '71',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'CUSTOMER_LOCATION_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_LOCATION_SAP',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '72',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'CUSTOMER_LOCATION_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_LOCATION_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '73',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_SAP',
	'UC': False
},
# {
# 	'PartitionKey': '1',
# 	'RowKey': '74',
# 	'ACTIVE': True,
# 	'INCREMENTAL': True,
# 	'NOTEBOOK_LEVEL': 1,
# 	'NOTEBOOK_NAME': 'ACCOUNT_KGD',
# 	'PRUNE_DAYS': 1,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_KGD',
# 	'UC': True
# },
{
	'PartitionKey': '1',
	'RowKey': '75',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TERRITORY_SAP',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_SAP',
	'UC': False
},
# {
# 	'PartitionKey': '1',
# 	'RowKey': '76',
# 	'ACTIVE': True,
# 	'INCREMENTAL': True,
# 	'NOTEBOOK_LEVEL': 3,
# 	'NOTEBOOK_NAME': 'ACCOUNT_AGG',
# 	'PRUNE_DAYS': 1,
# 	'PUBLISH': True,
# 	'TABLE_NAME': 'ACCOUNT_AGG',
# 	'UC': True
# },
{
	'PartitionKey': '1',
	'RowKey': '77',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'CUSTOMER_LOCATION_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_LOCATION_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '78',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'CUSTOMER_SALES_ORGANIZATION_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_SALES_ORGANIZATION_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '79',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'EXCHANGE_RATE_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'EXCHANGE_RATE_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '80',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'LEDGER_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'LEDGER_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '81',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'GROUPINGS_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'GROUPINGS_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '82',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'ORIGIN_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'ORIGIN_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '83',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PARTY_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PARTY_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '84',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PAYMENT_METHODS_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PAYMENT_METHODS_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '85',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PAYMENT_TERMS_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PAYMENT_TERMS_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '86',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PRODUCT_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '87',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '88',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PRODUCT_ORIGIN_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORIGIN_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '89',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'PRODUCT_REGION_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_REGION_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '90',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'SALES_BUDGET_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_BUDGET_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '91',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'SALES_FORECAST_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_FORECAST_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '92',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'SUPPLIER_ACCOUNT_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'SUPPLIER_ACCOUNT_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '93',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'SALES_ORGANIZATION_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'SALES_ORGANIZATION_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '94',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'AVERAGE_UNIT_PRICE_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'AVERAGE_UNIT_PRICE_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '95',
	'ACTIVE': False,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'BILL_TO_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'BILL_TO_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '96',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'CUSTOMER_ITEMS_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'CUSTOMER_ITEMS_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '97',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'TERRITORY_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '98',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '99',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'USER_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'USER_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '100',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'TERRITORY_ASSIGNMENTS_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_ASSIGNMENTS_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '101',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'ACCOUNT_ORGANIZATION_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'ACCOUNT_ORGANIZATION_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '102',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'ORGANIZATION_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '103',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'ORIGIN_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORIGIN_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '104',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'ORGANIZATION_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'ORGANIZATION_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '105',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '106',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '107',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TERRITORY_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '108',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '109',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_TOT',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '110',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TERRITORY_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_TOT',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '111',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TERRITORY_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TERRITORY_COL',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '112',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'PRODUCT_ORG_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'PRODUCT_ORG_COL',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '113',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SUBSTITUTION_MASTER_SPT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SUBSTITUTION_MASTER_SPT',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '114',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'USER_TWD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'USER_TWD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '115',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'AVERAGE_UNIT_PRICE_FC_SAPQV',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'AVERAGE_UNIT_PRICE_FC_SAPQV',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '116',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'AVERAGE_UNIT_PRICE_FC_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'AVERAGE_UNIT_PRICE_FC_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '117',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 3,
	'NOTEBOOK_NAME': 'SUBSTITUTION_MASTER_AGG',
	'PRUNE_DAYS': 1,
	'PUBLISH': True,
	'TABLE_NAME': 'SUBSTITUTION_MASTER_AGG',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '118',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'SUPPLIER_LOCATION_AGG',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'SUPPLIER_LOCATION_AGG',
	'UC': False
},
{
    'PartitionKey': '1',
    'RowKey': '119',
    'ACTIVE': True,
    'INCREMENTAL': False,
    'NOTEBOOK_LEVEL': 1,
    'NOTEBOOK_NAME': 'PRODUCT_REGION_PDH',
    'PRUNE_DAYS': 10,
    'PUBLISH': True,
    'TABLE_NAME': 'PRODUCT_REGION_PDH',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '120',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'CAPACITY_MASTER_TMB2',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CAPACITY_MASTER_TMB2',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '121',
	'ACTIVE': True,
	'INCREMENTAL': False,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'CAPACITY_MASTER_AGG',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'CAPACITY_MASTER_AGG',
	'UC': False
}, 
{
	'PartitionKey': '1',
	'RowKey': '122',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'TRANSACTION_TYPE_SF',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'TRANSACTION_TYPE_SF',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '123',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'COUNTRY_COL',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'COUNTRY_COL',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '124',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'COUNTRY_EBS',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'COUNTRY_EBS',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '125',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'COUNTRY_KGD',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'COUNTRY_KGD',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '126',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'COUNTRY_SAP',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'COUNTRY_SAP',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '127',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 1,
	'NOTEBOOK_NAME': 'COUNTRY_TOT',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'COUNTRY_TOT',
	'UC': False
},
{
	'PartitionKey': '1',
	'RowKey': '128',
	'ACTIVE': True,
	'INCREMENTAL': True,
	'NOTEBOOK_LEVEL': 2,
	'NOTEBOOK_NAME': 'COUNTRY_AGG',
	'PRUNE_DAYS': 10,
	'PUBLISH': True,
	'TABLE_NAME': 'COUNTRY_AGG',
	'UC': False
}
]

# COMMAND ----------


