# Databricks notebook source
config = [
{
	'PartitionKey': '1',
	'RowKey': '1',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': True,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_tickets',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '2',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_users',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '3',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_groups',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '4',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_locations',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '5',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': '',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_itilcategories',
	'TIMESTAMP_COLUMN': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '6',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_requesttypes',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '7',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': '',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_groups_tickets',
	'TIMESTAMP_COLUMN': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '8',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': '',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_tickets_users',
	'TIMESTAMP_COLUMN': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '9',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_slas',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '10',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_ticketsatisfactions'
}, 
{
	'PartitionKey': '1',
	'RowKey': '11',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': '',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_groups_users',
	'TIMESTAMP_COLUMN': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '12',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': '',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_entities',
	'TIMESTAMP_COLUMN': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '13',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': True,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_logs',
	'TIMESTAMP_COLUMN': 'date_mod'
}, 
{
	'PartitionKey': '1',
	'RowKey': '14',
	'ACTIVE': True,
	'HANDLE_DELETE': True,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': '',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_items_tickets',
	'TIMESTAMP_COLUMN': ''
}, 
{
	'PartitionKey': '1',
	'RowKey': '15',
	'ACTIVE': True,
	'HANDLE_DELETE': False,
	'INCREMENTAL': False,
	'PARTITION_COLUMN': 'date_mod',
	'PK': 'id',
	'PRUNE_DAYS': 90,
	'PUBLISH': True,
	'TABLE_NAME': 'glpi_monitors',
	'TIMESTAMP_COLUMN': 'date_mod'
}]


# COMMAND ----------


