# Databricks notebook source
config = [
{
    'PartitionKey': '1',
    'RowKey': '1',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': True,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_tickets'
},
{
    'PartitionKey': '1',
    'RowKey': '2',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_users'
},
{
    'PartitionKey': '1',
    'RowKey': '3',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_groups'
},
{
    'PartitionKey': '1',
    'RowKey': '4',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_locations'
},
{
    'PartitionKey': '1',
    'RowKey': '5',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_itilcategories'
},
{
    'PartitionKey': '1',
    'RowKey': '6',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_requesttypes'
},
{
    'PartitionKey': '1',
    'RowKey': '7',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_groups_tickets'
},
{
    'PartitionKey': '1',
    'RowKey': '8',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_tickets_users'
},
{
    'PartitionKey': '1',
    'RowKey': '9',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_slas'
},
{
    'PartitionKey': '1',
    'RowKey': '10',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_ticketsatisfactions'
},
{
    'PartitionKey': '1',
    'RowKey': '11',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_groups_users'
},
{
    'PartitionKey': '1',
    'RowKey': '12',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_entities'
},
{
    'PartitionKey': '1',
    'RowKey': '13',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': True,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_logs'
},
{
    'PartitionKey': '1',
    'RowKey': '14',
    'ACTIVE': True,
    'HANDLE_DELETE': True,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_items_tickets'
},
{
    'PartitionKey': '1',
    'RowKey': '15',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': 'date_mod',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': 'date_mod',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_monitors'
},
{
    'PartitionKey': '1',
    'RowKey': '16',
    'ACTIVE': True,
    'HANDLE_DELETE': False,
    'INCREMENTAL': False,
    'INCREMENTAL_COLUMN': '',
    'KEY_COLUMNS': 'id',
    'PARTITION_COLUMN': '',
    'PRUNE_DAYS': '90',
    'PUBLISH': True,
    'TABLE_NAME': 'glpi_changes'
}
]

# COMMAND ----------


