# Databricks notebook source
schema = {
'Creation_Date':'timestamp',
'Order_Date':'date',  
'Line_ID':'string',  
'_ID':'string',
'Order_Status':'string',
'Customer_Number':'string',
'Customer_Name':'string',
'Product':'string',
'Product_Name':'string',
'Style':'string',
'Brand':'string',
'SBU':'string',
'Region':'string',
'Sub_Region':'string',
'Channel':'string',
'Warehouse':'string',
'Origin_Code':'string',  
'Origin_Name':'string',
'Ordered_Currency':'string',
'Ordered_Qty_Ans_Std_Uom':'decimal(22,7)',
'Ordered_Amount_Doc_Currency':'decimal(22,7)',
'Ordered_Amount_USD':'decimal(22,7)',
'_PART':'date',
}
