# Databricks notebook source
schema = {
  'item_ID':'string',
  'inventoryWarehouse_ID':'string',
  'owningBusinessUnit_ID':'string',
  'MONTH_END_DATE' : 'DATE',
  'INVENTORY_ORG' : 'string',
  'INVENTORY_ORG_NAME' : 'string',
  'OPERATING_UNIT' : 'string',
  'DIVISION' : 'string',
  'ITEM_NUMBER' : 'string',
  'ITEM_DESCRIPTION' : 'string',
  'LEGACY_ASPN' : 'string',
  'LAUNCH_DATE' : 'DATE',
  'STD_UOM' : 'int',
  'ON_HAND_QTY' : 'decimal(22,7)',
  'INTRANSIT_QTY' : 'decimal(22,7)',
  'INV_M0_QTY' : 'decimal(22,7)',
  'INV_M1_QTY' : 'decimal(22,7)',
  'INV_M2_QTY' : 'decimal(22,7)',
  'INV_M3_QTY' : 'decimal(22,7)',
  'ONHAND_SEE_THROUGH_COST' : 'decimal(22,7)',
  'INTRANSIT_SEE_THROUGH_COST' : 'decimal(22,7)',
  'INTEGRATION_ID' : 'string',
  'DATASOURCE_NUM_ID' : 'int',
  'ETL_PROC_WID' : 'int',
  'EXCH_RATE' : 'decimal(22,7)',
  'UNIT_COST_STD_UOM': 'decimal(22,7)',
  '_PART':'date',
}
