# Databricks notebook source
schema = {
  'ITEM_NUMBER':'string',
  'ITEM_DESCRIPTION':'string',
  'SUBBRAND':'string',
  'INVENTORY_ORG':'string',
  'IN_TRANSIT_QTY' : 'decimal(22,7)',
  'IN_TRANSIT_QTY_STD_UOM' : 'decimal(22,7)',
  'PRIMARY_UOM':'string',
  'ANSELL_STD_UOM':'string',
  'DATASOURCE_NUM_ID' : 'int',
  'INTEGRATION_ID':'string',
  'DELETE_FLG':'string',
  'TENANT_ID':'string',
  'CREATED_BY_ID':'string',
  'CHANGED_BY_ID':'string',
  'CREATED_ON_DT' : 'DATE',
  'CHANGED_ON_DT' : 'DATE',
  'SUPPLIER_SITE_CODE':'string',
  'SUPPLIER_NAME':'string',
  'PO_VENDOR_NUMBER':'string',
  'PO_QTY_PRIMARY_UOM':'string',
  'PO_QTY_STD_UOM':'string',
  'TRANSACTION_DATE' : 'DATE',
  'ORDER_NUMBER':'string',
  'SOURCE_ORG_CODE':'string',
  'ORDER_TYPE_TEXT':'string',
  'ACTION':'string',
  'DUE_DATE' : 'DATE',
  'NEED_BY_DATE' : 'DATE',
  'PROMISE_DATE' : 'DATE',
  'RETD' : 'DATE',
  'CETD' : 'DATE',
  'VENDOR_NUM':'string',
  'VENDOR_ID':'string',
  '_PART':'date',
}
