# Databricks notebook source
schema = {
  'OPERATING_UNIT':'string',
  'ORDER_NUM':'string',
  'ORDER_LINE_NUM':'decimal(22,7)',
  'ORDER_LINE_DETAIL_NUM':'decimal(22,7)',
  'INVOICE_NUMBER':'string',
  'CIE':'string',
  'QTY_SHIPPED':'decimal(38,2)',
  'SHIPPED_DT':'timestamp',
  'CUST_NUM':'string',
  'PROD_NUM':'string',
  'PROD_NAME':'string',
  'BRAND':'string',
  'SUBBRAND':'string',
  'UNIT_PRICE':'decimal(38,5)',
  'INVOICE_DT':'date',
  'FISCAL_YEAR':'int',
  'FISCAL_PERIOD':'string',
  'CALENDER_YEAR':'int',
  'SHIPTO_SITE':'string',
  'STD_UOM':'string',
  'DIRECT_SHIPMENT':'string',
  'salesorderDetailId':'string',
  '_PART':'date',
}
