# Databricks notebook source
schema = {  
  'FISCAL_PERIOD':'string',
  'FISCAL_YEAR':'string',
  'INVENTORY_ORG_CODE':'string',
  'INVENTORY_ORG_NAME':'string',
  'OPERATING_UNIT':'string',
  'GL_ACCOUNT':'string',
  'VENDOR_NUMBER':'string',
  'VENDOR_NAME':'string',
  'PRODUCT_NUMBER':'string',
  'PRODUCT_NAME':'string',
  'PRODUCT_TYPE':'string',
  'PRIMARY_UOM':'string',
  'PO_DATE' : 'DATE',
  'PO_NUMBER':'string',
  'PO_LINE_NUMBER':'string',
  'RECEIVING_NUMBER':'string',
  'TRANSACTION_DATE' : 'DATE',
  'PURCHASE_CURRENCY':'string',
  'PURCHASE_UOM':'string',
  'UNITS_RECEIVED_PURCH_UOM' : 'decimal(22,7)',
  'STD_COST' : 'decimal(22,7)',
  'MARKUP' : 'decimal(22,7)',
  'TOTAL_COST' : 'decimal(22,7)',
  'BASE_CURR':'string',
  'UNIT_OF_MEASURE':'string',
  'PO_COST_UNIT' : 'decimal(22,7)',
  'TRANSACTION_AMT_TR_CURR' : 'decimal(22,7)',
  'TRANSACTION_AMT_LE_CURR' : 'decimal(22,7)',
  'UNITS_RCV_PRIMARY_UOM' : 'decimal(22,7)',
  'EXT_STD_COST' : 'decimal(22,7)',
  'FULL_NAME':'string',
  'INVENTORY_ITEM_ID':'string',
  'TRANSACTION_ID':'string',
  'LAST_UPDATE_DATE' : 'DATE',
  'LAST_UPDATED_BY':'string',
  'CREATION_DATE' : 'DATE',
  'CREATED_BY':'string',
  'ORGANIZATION_ID':'string',
  'CONVERSION_RATE' : 'decimal(22,7)',
  'PO_HEADER_ID':'string',
  'PO_LINE_ID':'string',
  'GL_COMPANY':'string',
  'GL_COST_CENTRE':'string',
  'GL_DIVISION':'string',
  'GL_REGION':'string',
  'GL_IC':'string',
  'GL_FUTURE':'string',
  'CODE_COMBINATION_ID':'string',
  'PRODUCT_DIVISION_DH':'string',
  'TRANSFER_PRICE_CATEGORY_DH':'string',
  'BRAND_DH':'string',
  'BRAND_TYPE':'string',
  'MASTER_BRAND':'string',
  'PRODUCT_FAMILY':'string',
  'EXCHANGERATE_USD':'decimal(22,7)',
  'SUB_BRAND_DH':'string',
  '_PART':'date',
}
