# Databricks notebook source
schema = {
	'createdBy':'string',
	'createdOn':'timestamp',
	'modifiedBy':'string',
	'modifiedOn':'timestamp',
	'insertedOn':'timestamp',
	'updatedOn':'timestamp',
	'baseCurrencyId':'string',
	'billToAddressId':'string',
	'billToCity':'string',
	'billToCountry':'string',
	'billToLine1':'string',
	'billToLine2':'string',
	'billToLine3':'string',
	'billToPostalCode':'string',
	'billToState':'string',
	'client':'string',
    'customerDivision':'string',
	'customerId':'string',
	'dateInvoiced':'date',
	'dateInvoiceRecognition':'date',
	'distributionChannel':'string',
	'exchangeRate':'decimal(22,7)',
    'exchangeRateDate':'date',
    'exchangeRateType':'string',
	'exchangeRateUSD':'decimal(22,7)',
    'exchangeSpotRate':'decimal(22,7)',
	'freightAmount':'decimal(22,7)',
	'invoiceId':'string',
	'invoiceNumber':'string',
	'owningBusinessUnitId':'string',
    'partyId':'string',
    'PayerAddressId':'string',
	'salesGroup':'string',
	'salesOffice':'string',
    'salesOrganization':'string',
    'salesOrganizationID':'string',
	'shipToAddressId':'string',
	'shipToCity':'string',
	'shipToCountry':'string',
	'shipToLine1':'string',
	'shipToLine2':'string',
	'shipToLine3':'string',
	'shiptoName':'string',
	'shipToPostalCode':'string',
	'shipToState':'string',
    'soldToAddressId':'string',
	'territoryId':'string',
	'totalAmount':'decimal(22,7)',
	'totalTax':'decimal(22,7)',
	'transactionCurrencyId':'string',
    'transactionId':'string',
	'_SOURCE':'string',
	'_ID':'string',
	'createdBy_ID':'string',
	'modifiedBy_ID':'string',
    'billToAddress_ID': 'string',
    'customer_ID': 'string',
    'customerOrganization_ID':'string',
    'owningBusinessUnit_ID': 'string',
    'shipToAddress_ID': 'string',
    'soldToAddress_ID':'string',
    'PayerAddress_ID':'string',
    'salesOrganization_ID':'string',
    'territory_ID': 'string',
    'party_ID':'string',
    'transaction_ID':'string',
    '_PART': 'date',
    '_DELETED': 'boolean',
    '_MODIFIED': 'timestamp'
}
