# Databricks notebook source
schema = {
	'createdBy':'string',
	'createdOn':'timestamp',
	'modifiedBy':'string',
	'modifiedOn':'timestamp',
	'insertedOn':'timestamp',
	'updatedOn':'timestamp',
    'baseCurrencyId':'string',
    'cancelReason':'string',
    'cancellationID':'string',
    'cancelledAmount':'decimal(22,7)',
    'cancelledListAmount':'decimal(22,7)',
    'cancelledDate':'date',
    'cancelledQuantity':'decimal(22,7)',
    'exchangeRate':'decimal(22,7)',
    'histTypeCode':'string',
    'inventoryWarehouseID':'string',
    'itemID':'string',
    'latestQuantityCancelled':'decimal(22,7)',
    'lineNumber':'string',
    'orderNumber':'string',
    'orderStatus':'string',
    'orderUomCode':'string',
    'owningBusinessUnitId':'string',
    'quantityOrdered':'decimal(22,7)',
    'reasonCode':'string',
    'reasonComment':'string',
    'salesorderDetailId':'string',
    'salesOrderId':'string',
    'sequenceNumber':'int',
    'transactionCurrencyId':'string',
	'_SOURCE':'string',
	'_ID':'string',
	'inventoryWarehouse_ID':'string',
	'item_ID':'string',
    'owningBusinessUnit_ID':'string',
	'salesOrder_ID':'string',
    'salesorderDetail_ID':'string',
	'createdBy_ID':'string',
	'modifiedBy_ID':'string',
    '_DELETED':'boolean',
    '_PART': 'date',
    '_MODIFIED': 'timestamp'
}
