# Databricks notebook source
schema = {
	'createdBy' : 'string',
    'createdOn' : 'timestamp',
    'modifiedBy' : 'string',
    'modifiedOn' : 'timestamp',
    'insertedOn' : 'timestamp',
    'updatedOn' : 'timestamp',
    'currencyCode' : 'string',
    'endDate' : 'date',
    'freightTermsCode' : 'string',
    'listTypeCode' : 'string',
    'priceListComment' : 'string',
    'priceListDescription' : 'string',
    'priceListHeaderId' : 'string',
    'priceListName' : 'string',
    'programApplicationId' : 'string',
    'programId' : 'string',
    'programUpdateDate' : 'date',
    'roundingFactor' : 'decimal(22,7)',
    'shipMethodCode' : 'string',
    'startDate' : 'date',
    '_SOURCE' : 'string',
    '_ID' : 'string',
    'createdBy_ID' : 'string',
    'modifiedBy_ID' : 'string',
    '_PART': 'date',
    '_DELETED': 'boolean',
    '_MODIFIED': 'timestamp'
}
