# Databricks notebook source
schema = {
	'createdBy' : 'string',
    'createdOn' : 'timestamp',
    'modifiedBy' : 'string',
    'modifiedOn' : 'timestamp',
    'insertedOn' : 'timestamp',
    'updatedOn' : 'timestamp',
    'endDate' : 'date',
    'percentPrice' : 'decimal(22,7)',
    'priceByFormulaId' : 'string',
    'priceListHeaderId' : 'string',
    'priceListlineAttribute1' : 'string',
    'priceListlineAttribute10' : 'string',
    'priceListlineAttribute11' : 'string',
    'priceListlineAttribute12' : 'string',
    'priceListlineAttribute13' : 'string',
    'priceListlineAttribute14' : 'string',
    'priceListlineAttribute15' : 'string',
    'priceListlineAttribute2' : 'string',
    'priceListlineAttribute3' : 'string',
    'priceListlineAttribute4' : 'string',
    'priceListlineAttribute5' : 'string',
    'priceListlineAttribute6' : 'string',
    'priceListlineAttribute7' : 'string',
    'priceListlineAttribute8' : 'string',
    'priceListlineAttribute9' : 'string',
    'priceListLineComment' : 'string',
    'priceListItemNumber' : 'string',
    'priceListItemId' : 'string',
    'priceListProductLevel' : 'string',
    'unitPrice' : 'decimal(22,7)',
    'productUomCode' : 'string',
    'priceListLineId' : 'string',
    'primaryUomFlag': 'boolean',
    'programApplicationId' : 'string',
    'programId' : 'string',
    'programUpdateDate' : 'date',
    'startDate' : 'date',
    'unitListPrice' : 'decimal(22,7)',
    '_SOURCE' : 'string',
    '_ID' : 'string',
    'createdBy_ID' : 'string',
    'modifiedBy_ID' : 'string',
    'priceListHeader_ID' : 'string',
    'priceListItem_ID' : 'string',
    '_PART': 'date',
    '_DELETED': 'boolean',
    '_MODIFIED': 'timestamp'
}
